var f=!0,h=null,j=!1,l,n=[],o=[];function p(){this.contents=[];this.e=h}function q(a,b,c){a.a={y:b,x:c}}function r(){p.call(this)}r.prototype=new p;l=r.prototype;l.b="empty";l.type=r;l.f=f;l.l=f;l.description="empty space";l.g=500;function s(){p.call(this)}s.prototype=new p;l=s.prototype;l.b="wall";l.type=s;l.f=j;l.description="wall";l.g=500;function t(){p.call(this);this.moveTo=h}t.prototype=new p;l=t.prototype;l.b="agent";l.type=t;l.selected=j;l.description="sandwich maker";l.c=h;
l.d=function(){u(this,n);this.c=h};
l.j=function(){if(this.c){for(var a=[],b=0;b<v.length;b++){var c=w(v[b],this.c.a);x[c.y][c.x].f&&a.push({y:c.y,x:c.x})}1<a.length&&(a=y(this.a,a));if(0<a.length){for(b=0;b<a.length;b++){a:{c=a[b];c=x[c.y][c.x];if(0!=c.contents.length)for(var d=0;d<c.contents.length;d++)if(c.contents[d].type==this.type&&c.contents[d]!=this){c=j;break a}c=f}if(c){var e=a[b];break}}e||(e=a[0]);this.moveTo=e}else this.moveTo=this.c=h;e&&(e.y==this.a.y&&e.x==this.a.x)&&(this.c.h+=10)}if(this.moveTo&&(this.a.y!=this.moveTo.y||
this.a.x!=this.moveTo.x)){if(e=z(x,this.a,this.moveTo))a=this.a,b=x,e=w(e[0],a),b[e.y][e.x].contents.push(this),b[a.y][a.x].contents.pop(),this.a=e}else if(!this.c&&0<o.length){a=[];for(b=0;b<o.length;b++){e=j;for(c=0;c<n.length;c++)if(n[c].c==o[b]){e=f;break}e||a.push(o[b].a)}0<a.length&&(1!=a.length&&y(this.a,a),this.c=x[a[0].y][a[0].x])}else if((a=x[this.a.y][this.a.x].contents)&&1<a.length&&a[a.length-1]==this){a=A();for(b=0;b<a.length;b++)if(e=w(a[b],this.a),c=x[e.y][e.x],c.f&&0==c.contents.length){this.moveTo=
e;break}}this.moveTo&&(this.a.y==this.moveTo.y&&this.a.x==this.moveTo.x)&&(this.moveTo=h);if(!this.moveTo&&(a=Math.random(),0.96<a&&0.999>a)){a=A();for(b=0;b<a.length;b++){e=A();for(c=0;c<a.length;c++){var d=w(e[c],w(a[b],this.a)),g;a:{try{if(0>d.y||d.y>x.length-1||0>d.x||d.x>x[d.y].length-1){g=j;break a}}catch(m){throw Error("Error in map bounds check");}g=f}if(g&&x[d.y][d.x].f){this.moveTo=d;break}if(this.moveTo)break}}}};function B(){p.call(this)}B.prototype=new p;l=B.prototype;l.f=j;l.type=B;
l.description="something being built";l.h=h;l.g=h;l.k=h;l.d=function(){u(this,o);for(var a=0;a<n.length;a++)n[a].c==this&&(n[a].c=h)};l.j=function(){if(this.h>=this.g){var a=this.k,b=this.a.y,c=this.a.x;q(a,b,c);a.contents=this.contents;this.d&&this.d();x[b][c]=a}else a=100*(this.h/this.g),0===a?this.e="markedForConstruction":25>=a?this.e="oneFourthConstructed":25<a&&50>=a?this.e="oneHalfConstructed":50<a&&75>=a?this.e="threeFourthsConstructed":75<a&&(this.e="almostConstructed")};
var C=[{b:"agent",select:t},{b:"picker",select:0},{b:"inspector",select:2},{b:"delete",select:1},{b:"wall",select:s},{b:"emptySelector",select:r}],D=0,E=h,F=h,v="north northeast east southeast south southwest west northwest".split(" "),x=[],G=[],H=[],I=h,J=20,K=40,aa=0,L=0;function M(a,b){return a.i-b.i}function N(a){switch(a){case "east":case "west":return 0;case "north":case "northeast":case "northwest":return-1;case "south":case "southeast":case "southwest":return 1}}
function O(a){switch(a){case "north":case "south":return 0;case "northeast":case "east":case "southeast":return 1;case "southwest":case "west":case "northwest":return-1}}function ba(a){switch(a){case "north":return"south";case "northeast":return"southwest";case "east":return"west";case "southeast":return"northwest";case "south":return"north";case "southwest":return"northeast";case "west":return"east";case "northwest":return"southeast";default:throw Error("ReverseDir error");}}
function A(){for(var a=[],b=[],c=0;c<v.length;c++)a.push(v[c]);for(c=0;c<v.length;c++){var d=Math.round(Math.random()*(a.length-1));b.push(a[d]);d<a.length&&(a[d]=a[a.length-1]);a.pop()}return b}function w(a,b){return{y:b.y+N(a),x:b.x+O(a)}}
function z(a,b,c){for(var d=[],e=0;e<a.length;e++)d.push({});d[b.y][b.x]=0;for(var g=[{i:0,x:b.x,y:b.y}];0<g.length;){b=A();for(e=0;e<b.length;e++){var m=N(b[e]),k=O(b[e]),i={i:d[g[0].y][g[0].x]+1,x:g[0].x+k,y:g[0].y+m};0<=i.y&&(i.y<a.length&&0<=i.x&&i.x<a[i.y].length)&&(a[g[0].y+m][g[0].x+k].f&&"undefined"==typeof d[g[0].y+m][g[0].x+k])&&(d[i.y][i.x]=i.i,g.push(i))}g.shift();g.sort(M)}if("undefined"==typeof d[c.y][c.x])return j;a=c;for(c=[];0!=d[a.y][a.x];){b=A();for(e=0;e<b.length;e++)if(g=w(b[e],
a),m=d[g.y][g.x],"undefined"!=typeof m&&m<d[a.y][a.x]){c.push(ba(b[e]));a=g;break}}return c=c.reverse()}function y(a,b){for(var c=x,d=0;d<b.length;d++){var e=z(c,a,b[d]);e?b[d].i=e.length:u(b[d],b)}b.sort(M);return b}function u(a,b){for(var c=0;c<b.length;c++)a===b[c]&&(c<b.length-1&&(b[c]=b[b.length-1]),b.pop())}function P(a,b,c){if(0==x[b][c].contents.length&&x[b][c].type!=a.type){var d=new B;q(d,b,c);d.h=0;d.g=a.g;d.k=a;o.push(d);x[b][c]=d}}
function Q(){for(var a=0;a<o.length;a++)o[a].j();for(a=0;a<n.length;a++)n[a].j();for(var a=aa,b=L,c=0;c<J;c++){for(var d=0;d<K;d++){var e=G[c][d],g=x[a][b],m=$(e).attr("class").split(" "),k=["mapColumn"];k.push(g.b);g.e&&k.push(g.e);if(g.contents&&1<=g.contents.length){k.push(g.contents[0].b);for(var i=0;i<g.contents.length;i++)g.contents[i].selected&&k.push("mapSelected")}if(k.length!=m.length)$(e).removeClass(),$(e).addClass(k.join(" "));else for(i=0;i<k.length;i++)if(k[i]!=m[i]){$(e).removeClass();
$(e).addClass(k.join(" "));break}b++}b=L;a++}setTimeout(Q,100)}
for(var R="#######################;# #     ######        #;# # ###      #    #   #;# # #   ######    #   #;# # #  ##         #   #;# # #  #          #   #;# # #  ############   #;# # #      #          #;#   ######   #        #;#######################".split(";"),S=[],T=0;T<R.length;T++){for(var U=[],V=0;V<R[T].length;V++){var W;switch(R[T][V]){case " ":W=new r;q(W,T,V);break;case "#":W=new s;q(W,T,V);break;case "@":W=new r;q(W,T,V);W.contents=new t;break;default:throw Error("AsciiArtToMap error");
}U.push(W)}S.push(U)}for(var X=0;200>X;X++){for(var Y=[],Z=0;200>Z;Z++)if(S[X]&&S[X][Z])Y.push(S[X][Z]);else{var ca=new r;q(ca,X,Z);Y.push(ca)}x.push(Y)}
(function(){for(var a=0;a<J;a++){var b=$('<div class="mapRow"></div>',c),c=$("#Map");b.appendTo(c);for(var d=[],e=0;e<K;e++){var g=$('<div class="mapColumn"</div>',b);(function(a,b){g.mousedown(function(){switch(C[D].select){case 0:1<=x[a][b].contents.length&&(E&&(F=E,F.selected=j),E=x[a][b].contents[x[a][b].contents.length-1],E.selected=f);0==x[a][b].contents.length&&E&&(E.moveTo={y:a,x:b});break;case 1:if(0<x[a][b].contents.length){for(var c=0;c<x[a][b].contents.length;c++)x[a][b].contents[c].d&&
x[a][b].contents[c].d();x[a][b].contents=[]}x[a][b].d&&x[a][b].d();c=new r;q(c,a,b);x[a][b]=c;break;case 2:if(0<x[a][b].contents.length){for(var c=["Here are: "+x[a][b].description],d=0;d<x[a][b].contents.length;d++)c.push(x[a][b].contents[d].description);c=c.join(", ")}else c="Here is: "+x[a][b].description;$(I).text(c);break;case t:c=new t;c.type&&c.type==t?x[a][b].l&&0==x[a][b].contents.length&&(q(c,a,b),x[a][b].contents.push(c),n.push(c)):(q(c,a,b),x[a][b]=c);break;case s:P(new s,a,b);break;case r:P(new r,
a,b);break;default:throw Error("Error in MapInteract");}})})(a,e);g.appendTo(b);d.push(g)}G.push(d)}})();(function(){for(var a=0;a<C.length;a++){var b=$('<div class="paletteRow"></div>'),c=$("#Palette");b.appendTo(c);(function(a){b.mousedown(function(){var b=D;D=a;$(H[D]).addClass("paletteSelected");$(H[b]).removeClass("paletteSelected")})})(a);$(b).addClass(C[a].b);H.push(b)}D!=h&&$(H[D]).addClass("paletteSelected")})();var I=$('<div class="textRow"></div>'),da=$("#TextBox");I.appendTo(da);Q();
