var f=!0,h=null,j=!1,k,l=[],n=[];function o(){this.contents=[];this.e=h}function p(){o.call(this)}p.prototype=new o;k=p.prototype;k.b="empty";k.type=p;k.f=f;k.l=f;k.description="empty space";k.g=500;function q(){o.call(this)}q.prototype=new o;k=q.prototype;k.b="wall";k.type=q;k.f=j;k.description="wall";k.g=500;function r(){o.call(this);this.moveTo=h}r.prototype=new o;k=r.prototype;k.b="agent";k.type=r;k.selected=j;k.description="sandwich maker";k.c=h;k.d=function(){s(this,l);this.c=h};
k.j=function(){if(this.c){for(var a=[],b=0;b<t.length;b++){var c=u(t[b],this.c.a);v[c.y][c.x].f&&a.push({y:c.y,x:c.x})}1<a.length&&(a=w(this.a,a));if(0<a.length){for(b=0;b<a.length;b++){a:{c=a[b];c=v[c.y][c.x];if(0!=c.contents.length)for(var d=0;d<c.contents.length;d++)if(c.contents[d].type==this.type&&c.contents[d]!=this){c=j;break a}c=f}if(c){var e=a[b];break}}e||(e=a[0]);this.moveTo=e}else this.moveTo=this.c=h;e&&(e.y==this.a.y&&e.x==this.a.x)&&(this.c.h+=10)}if(this.moveTo&&(this.a.y!=this.moveTo.y||
this.a.x!=this.moveTo.x)){if(e=x(v,this.a,this.moveTo))a=this.a,b=v,e=u(e[0],a),b[e.y][e.x].contents.push(this),b[a.y][a.x].contents.pop(),this.a=e}else if(!this.c&&0<n.length){a=[];for(b=0;b<n.length;b++){e=j;for(c=0;c<l.length;c++)if(l[c].c==n[b]){e=f;break}e||a.push(n[b].a)}0<a.length&&(1!=a.length&&w(this.a,a),this.c=v[a[0].y][a[0].x])}else if((a=v[this.a.y][this.a.x].contents)&&1<a.length&&a[a.length-1]==this){a=y();for(b=0;b<a.length;b++)if(e=u(a[b],this.a),c=v[e.y][e.x],c.f&&0==c.contents.length){this.moveTo=
e;break}}this.moveTo&&(this.a.y==this.moveTo.y&&this.a.x==this.moveTo.x)&&(this.moveTo=h);if(!this.moveTo&&(a=Math.random(),0.96<a&&0.999>a)){a=y();for(b=0;b<a.length;b++){e=y();for(c=0;c<a.length;c++){var d=u(e[c],u(a[b],this.a)),g;a:{try{if(0>d.y||d.y>v.length-1||0>d.x||d.x>v[d.y].length-1){g=j;break a}}catch(i){throw Error("Error in map bounds check");}g=f}if(g&&v[d.y][d.x].f){this.moveTo=d;break}if(this.moveTo)break}}}};function z(){o.call(this)}z.prototype=new o;k=z.prototype;k.f=j;k.type=z;
k.description="something being built";k.h=h;k.g=h;k.k=h;k.d=function(){s(this,n);for(var a=0;a<l.length;a++)l[a].c==this&&(l[a].c=h)};k.j=function(){if(this.h>=this.g){var a=this.k,b=this.a.y,c=this.a.x;a.a={y:b,x:c};a.contents=this.contents;this.d&&this.d();v[b][c]=a}else a=100*(this.h/this.g),0===a?this.e="markedForConstruction":25>=a?this.e="oneFourthConstructed":25<a&&50>=a?this.e="oneHalfConstructed":50<a&&75>=a?this.e="threeFourthsConstructed":75<a&&(this.e="almostConstructed")};
var A=[{b:"agent",select:r},{b:"picker",select:0},{b:"inspector",select:2},{b:"delete",select:1},{b:"wall",select:q},{b:"emptySelector",select:p}],B=0,C=h,D=h,t="north northeast east southeast south southwest west northwest".split(" "),v=[],E=[],F=[],G=h;function H(a,b){return a.i-b.i}function J(a){switch(a){case "east":case "west":return 0;case "north":case "northeast":case "northwest":return-1;case "south":case "southeast":case "southwest":return 1}}
function K(a){switch(a){case "north":case "south":return 0;case "northeast":case "east":case "southeast":return 1;case "southwest":case "west":case "northwest":return-1}}function L(a){switch(a){case "north":return"south";case "northeast":return"southwest";case "east":return"west";case "southeast":return"northwest";case "south":return"north";case "southwest":return"northeast";case "west":return"east";case "northwest":return"southeast";default:throw Error("ReverseDir error");}}
function y(){for(var a=[],b=[],c=0;c<t.length;c++)a.push(t[c]);for(c=0;c<t.length;c++){var d=Math.round(Math.random()*(a.length-1));b.push(a[d]);d<a.length&&(a[d]=a[a.length-1]);a.pop()}return b}function u(a,b){return{y:b.y+J(a),x:b.x+K(a)}}
function x(a,b,c){for(var d=[],e=0;e<a.length;e++)d.push({});d[b.y][b.x]=0;for(var g=[{i:0,x:b.x,y:b.y}];0<g.length;){b=y();for(e=0;e<b.length;e++){var i=J(b[e]),I=K(b[e]),m={i:d[g[0].y][g[0].x]+1,x:g[0].x+I,y:g[0].y+i};0<=m.y&&(m.y<a.length&&0<=m.x&&m.x<a[m.y].length)&&(a[g[0].y+i][g[0].x+I].f&&"undefined"==typeof d[g[0].y+i][g[0].x+I])&&(d[m.y][m.x]=m.i,g.push(m))}g.shift();g.sort(H)}if("undefined"==typeof d[c.y][c.x])return j;a=c;for(c=[];0!=d[a.y][a.x];){b=y();for(e=0;e<b.length;e++)if(g=u(b[e],
a),i=d[g.y][g.x],"undefined"!=typeof i&&i<d[a.y][a.x]){c.push(L(b[e]));a=g;break}}return c=c.reverse()}function w(a,b){for(var c=v,d=0;d<b.length;d++){var e=x(c,a,b[d]);e?b[d].i=e.length:s(b[d],b)}b.sort(H);return b}function s(a,b){for(var c=0;c<b.length;c++)a===b[c]&&(c<b.length-1&&(b[c]=b[b.length-1]),b.pop())}function M(a,b,c){if(0==v[b][c].contents.length&&v[b][c].type!=a.type){var d=new z;d.a={y:b,x:c};d.h=0;d.g=a.g;d.k=a;n.push(d);v[b][c]=d}}
function N(){for(var a=0;a<n.length;a++)n[a].j();for(a=0;a<l.length;a++)l[a].j();for(a=0;a<v.length;a++)for(var b=0;b<v[a].length;b++){var c=E[a][b],d=v[a][b],e=$(c).attr("class").split(" "),g=["mapColumn"];g.push(d.b);d.e&&g.push(d.e);if(d.contents&&1<=d.contents.length){g.push(d.contents[0].b);for(var i=0;i<d.contents.length;i++)d.contents[i].selected&&g.push("mapSelected")}if(g.length!=e.length)$(c).removeClass(),$(c).addClass(g.join(" "));else for(i=0;i<g.length;i++)if(g[i]!=e[i]){$(c).removeClass();
$(c).addClass(g.join(" "));break}}setTimeout(N,100)}
for(var O="#######################;# #     ######        #;# # ###      #    #   #;# # #   ######    #   #;# # #  ##         #   #;# # #  #          #   #;# # #  ############   #;# # #      #          #;#   ######   #        #;#######################".split(";"),P=[],Q=0;Q<O.length;Q++){for(var R=[],S=0;S<O[Q].length;S++){var T;switch(O[Q][S]){case " ":T=new p;T.a={y:Q,x:S};break;case "#":T=new q;T.a={y:Q,x:S};break;case "@":T=new p;T.a={y:Q,x:S};T.contents=new r;break;default:throw Error("AsciiArtToMap error");
}R.push(T)}P.push(R)}for(var U=0;U<P.length;U++){for(var V=[],W=0;W<P[U].length;W++)V.push(P[U][W]);v.push(V)}
(function(){for(var a=0;a<v.length;a++){var b=$('<div class="mapRow"></div>',c),c=$("#Map");b.appendTo(c);for(var d=[],e=0;e<v[a].length;e++){var g=$('<div class="mapColumn"</div>',b);(function(a,b){g.mousedown(function(){switch(A[B].select){case 0:1<=v[a][b].contents.length&&(C&&(D=C,D.selected=j),C=v[a][b].contents[v[a][b].contents.length-1],C.selected=f);0==v[a][b].contents.length&&C&&(C.moveTo={y:a,x:b});break;case 1:if(0<v[a][b].contents.length){for(var c=0;c<v[a][b].contents.length;c++)v[a][b].contents[c].d&&
v[a][b].contents[c].d();v[a][b].contents=[]}v[a][b].d&&v[a][b].d();c=new p;c.a={y:a,x:b};v[a][b]=c;break;case 2:if(0<v[a][b].contents.length){for(var c=["Here are: "+v[a][b].description],d=0;d<v[a][b].contents.length;d++)c.push(v[a][b].contents[d].description);c=c.join(", ")}else c="Here is: "+v[a][b].description;$(G).text(c);break;case r:c=new r;c.type&&c.type==r?v[a][b].l&&0==v[a][b].contents.length&&(c.a={y:a,x:b},v[a][b].contents.push(c),l.push(c)):(c.a={y:a,x:b},v[a][b]=c);break;case q:M(new q,
a,b);break;case p:M(new p,a,b);break;default:throw Error("Error in MapInteract");}})})(a,e);g.appendTo(b);d.push(g)}E.push(d)}})();(function(){for(var a=0;a<A.length;a++){var b=$('<div class="paletteRow"></div>'),c=$("#Palette");b.appendTo(c);(function(a){b.mousedown(function(){var b=B;B=a;$(F[B]).addClass("paletteSelected");$(F[b]).removeClass("paletteSelected")})})(a);$(b).addClass(A[a].b);F.push(b)}B!=h&&$(F[B]).addClass("paletteSelected")})();var G=$('<div class="textRow"></div>'),X=$("#TextBox");
G.appendTo(X);N();
