var f=!0,g=null,j=!1,k,l=[],m=[];function o(){this.contents=[];this.e=g}function p(){o.call(this)}p.prototype=new o;k=p.prototype;k.b="empty";k.type=p;k.f=f;k.l=f;k.description="empty space";k.g=500;function q(){o.call(this)}q.prototype=new o;k=q.prototype;k.b="wall";k.type=q;k.f=j;k.description="wall";k.g=500;function r(){o.call(this);this.moveTo=g}r.prototype=new o;k=r.prototype;k.b="agent";k.type=r;k.selected=j;k.description="sandwich maker";k.c=g;k.d=function(){s(this,l);this.c=g};
k.j=function(){if(this.c){for(var a=[],b=0;b<t.length;b++){var c=u(t[b],this.c.a);v[c.y][c.x].f&&a.push({y:c.y,x:c.x})}1<a.length&&(a=w(this.a,a));if(0<a.length){for(b=0;b<a.length;b++){a:{var d=a[b],c=r,d=v[d.y][d.x];if(0!=d.contents.length)for(var h=0;h<d.contents.length;h++)if(d.contents[h].type==c&&d.contents[h]!=this){c=j;break a}c=f}if(c){var e=a[b];break}}e||(e=a[0]);this.moveTo=e}else this.moveTo=this.c=g;e&&(e.y==this.a.y&&e.x==this.a.x)&&(this.c.h+=10)}if(this.moveTo&&(this.a.y!=this.moveTo.y||
this.a.x!=this.moveTo.x)){if(e=x(v,this.a,this.moveTo))a=this.a,b=v,e=u(e[0],a),b[e.y][e.x].contents.push(this),b[a.y][a.x].contents.pop(),this.a=e}else if(!this.c&&0<m.length){a=[];for(b=0;b<m.length;b++){e=j;for(c=0;c<l.length;c++)if(l[c].c==m[b]){e=f;break}e||a.push(m[b].a)}0<a.length&&(1!=a.length&&w(this.a,a),this.c=v[a[0].y][a[0].x])}else if((a=v[this.a.y][this.a.x].contents)&&1<a.length&&a[a.length-1]==this){a=y();for(b=0;b<a.length;b++)if(e=u(a[b],this.a),c=v[e.y][e.x],c.f&&0==c.contents.length){this.moveTo=
e;break}}this.moveTo&&(this.a.y==this.moveTo.y&&this.a.x==this.moveTo.x)&&(this.moveTo=g);if(!this.moveTo&&(a=Math.random(),0.96<a&&0.999>a)){a=y();for(b=0;b<a.length;b++){e=y();for(c=0;c<a.length;c++){var d=u(e[c],u(a[b],this.a)),i;a:{try{if(0>d.y||d.y>v.length-1||0>d.x||d.x>v[d.y].length-1){i=j;break a}}catch(B){throw Error("Error in map bounds check");}i=f}if(i&&v[d.y][d.x].f){this.moveTo=d;break}if(this.moveTo)break}}}};function z(){o.call(this)}z.prototype=new o;k=z.prototype;k.f=j;k.type=z;
k.description="something being built";k.h=g;k.g=g;k.k=g;k.d=function(){s(this,m);for(var a=0;a<l.length;a++)l[a].c==this&&(l[a].c=g)};k.j=function(){if(this.h>=this.g){var a=new this.k,b=this.a.y,c=this.a.x;a.a={y:b,x:c};a.contents=this.contents;this.d&&this.d();v[b][c]=a}else a=100*(this.h/this.g),0===a?this.e="markedForConstruction":25>=a?this.e="oneFourthConstructed":25<a&&50>=a?this.e="oneHalfConstructed":50<a&&75>=a?this.e="threeFourthsConstructed":75<a&&(this.e="almostConstructed")};
var A=[{b:"agent",select:r},{b:"picker",select:0},{b:"inspector",select:2},{b:"delete",select:1},{b:"wall",select:q},{b:"emptySelector",select:p}],C=0,D=g,E=g,t="north northeast east southeast south southwest west northwest".split(" "),v=[],F=[],G=[],H=g;function I(a,b){return a.i-b.i}function J(a){switch(a){case "east":case "west":return 0;case "north":case "northeast":case "northwest":return-1;case "south":case "southeast":case "southwest":return 1}}
function K(a){switch(a){case "north":case "south":return 0;case "northeast":case "east":case "southeast":return 1;case "southwest":case "west":case "northwest":return-1}}function L(a){switch(a){case "north":return"south";case "northeast":return"southwest";case "east":return"west";case "southeast":return"northwest";case "south":return"north";case "southwest":return"northeast";case "west":return"east";case "northwest":return"southeast";default:throw Error("ReverseDir error");}}
function y(){for(var a=[],b=[],c=0;c<t.length;c++)a.push(t[c]);for(c=0;c<t.length;c++){var d=Math.round(Math.random()*(a.length-1));b.push(a[d]);d<a.length&&(a[d]=a[a.length-1]);a.pop()}return b}function u(a,b){return{y:b.y+J(a),x:b.x+K(a)}}
function x(a,b,c){for(var d=[],h=0;h<a.length;h++)d.push({});d[b.y][b.x]=0;for(var e=[{i:0,x:b.x,y:b.y}];0<e.length;){b=y();for(h=0;h<b.length;h++){var i=J(b[h]),B=K(b[h]),n={i:d[e[0].y][e[0].x]+1,x:e[0].x+B,y:e[0].y+i};0<=n.y&&(n.y<a.length&&0<=n.x&&n.x<a[n.y].length)&&(a[e[0].y+i][e[0].x+B].f&&"undefined"==typeof d[e[0].y+i][e[0].x+B])&&(d[n.y][n.x]=n.i,e.push(n))}e.shift();e.sort(I)}if("undefined"==typeof d[c.y][c.x])return j;a=c;for(c=[];0!=d[a.y][a.x];){b=y();for(h=0;h<b.length;h++)if(e=u(b[h],
a),i=d[e.y][e.x],"undefined"!=typeof i&&i<d[a.y][a.x]){c.push(L(b[h]));a=e;break}}return c=c.reverse()}function w(a,b){for(var c=v,d=0;d<b.length;d++){var h=x(c,a,b[d]);h?b[d].i=h.length:s(b[d],b)}b.sort(I);return b}function s(a,b){for(var c=0;c<b.length;c++)a===b[c]&&(c<b.length-1&&(b[c]=b[b.length-1]),b.pop())}function M(a,b,c){var d=new a;0==v[b][c].contents.length&&v[b][c].type!=d.type&&(d=new z,d.a={y:b,x:c},d.h=0,d.g=a.prototype.g,d.k=a,m.push(d),v[b][c]=d)}
function N(){for(var a=0;a<m.length;a++)m[a].j();for(a=0;a<l.length;a++)l[a].j();for(a=0;a<v.length;a++)for(var b=0;b<v[a].length;b++){var c=F[a][b],d=v[a][b],h=$(c).attr("class").split(" "),e=["mapColumn"];e.push(d.b);d.e&&e.push(d.e);if(d.contents&&1<=d.contents.length){e.push(d.contents[0].b);for(var i=0;i<d.contents.length;i++)d.contents[i].selected&&e.push("mapSelected")}if(e.length!=h.length)$(c).removeClass(),$(c).addClass(e.join(" "));else for(i=0;i<e.length;i++)if(e[i]!=h[i]){$(c).removeClass();
$(c).addClass(e.join(" "));break}}setTimeout(N,100)}
for(var O="#######################;# #     ######        #;# # ###      #    #   #;# # #   ######    #   #;# # #  ##         #   #;# # #  #          #   #;# # #  ############   #;# # #      #          #;#   ######   #        #;#######################".split(";"),P=[],Q=0;Q<O.length;Q++){for(var R=[],S=0;S<O[Q].length;S++){var T;switch(O[Q][S]){case " ":T=new p;T.a={y:Q,x:S};break;case "#":T=new q;T.a={y:Q,x:S};break;case "@":T=new p;T.a={y:Q,x:S};T.contents=new r;break;default:throw Error("AsciiArtToMap error");
}R.push(T)}P.push(R)}for(var U=0;U<P.length;U++){for(var V=[],W=0;W<P[U].length;W++)V.push(P[U][W]);v.push(V)}
(function(){for(var a=0;a<v.length;a++){var b=$('<div class="mapRow"></div>',c),c=$("#Map");b.appendTo(c);for(var d=[],h=0;h<v[a].length;h++){var e=$('<div class="mapColumn"</div>',b);(function(a,b){e.mousedown(function(){switch(A[C].select){case 0:1<=v[a][b].contents.length&&(D&&(E=D,E.selected=j),D=v[a][b].contents[v[a][b].contents.length-1],D.selected=f);0==v[a][b].contents.length&&D&&(D.moveTo={y:a,x:b});break;case 1:if(0<v[a][b].contents.length){for(var c=0;c<v[a][b].contents.length;c++)v[a][b].contents[c].d&&
v[a][b].contents[c].d();v[a][b].contents=[]}v[a][b].d&&v[a][b].d();c=new p;c.a={y:a,x:b};v[a][b]=c;break;case 2:if(0<v[a][b].contents.length){for(var c=["Here are: "+v[a][b].description],d=0;d<v[a][b].contents.length;d++)c.push(v[a][b].contents[d].description);c=c.join(", ")}else c="Here is: "+v[a][b].description;$(H).text(c);break;case r:c=r;switch(c){case r:v[a][b].l&&0==v[a][b].contents.length&&(c=new r,c.a={y:a,x:b},v[a][b].contents.push(c),l.push(c));break;default:c=new c,c.a={y:a,x:b},v[a][b]=
c}break;case q:M(q,a,b);break;case p:M(p,a,b);break;default:throw Error("Error in MapInteract");}})})(a,h);e.appendTo(b);d.push(e)}F.push(d)}})();(function(){for(var a=0;a<A.length;a++){var b=$('<div class="paletteRow"></div>'),c=$("#Palette");b.appendTo(c);(function(a){b.mousedown(function(){var b=C;C=a;$(G[C]).addClass("paletteSelected");$(G[b]).removeClass("paletteSelected")})})(a);$(b).addClass(A[a].b);G.push(b)}C!=g&&$(G[C]).addClass("paletteSelected")})();
var H=$('<div class="textRow"></div>'),X=$("#TextBox");H.appendTo(X);N();
