var k=!0,q=null,t=!1;
(function(){var s,z;function n(){this.contents=[];this.f=q}function j(){n.call(this)}function m(){n.call(this)}function h(){n.call(this);this.moveTo=q}function l(){n.call(this)}function D(a,c){return a.j-c.j}function E(a){switch(a){case "east":case "west":return 0;case "north":case "northeast":case "northwest":return-1;case "south":case "southeast":case "southwest":return 1}}function F(a){switch(a){case "north":case "south":return 0;case "northeast":case "east":case "southeast":return 1;case "southwest":case "west":case "northwest":return-1}}
function N(a){switch(a){case "north":return"south";case "northeast":return"southwest";case "east":return"west";case "southeast":return"northwest";case "south":return"north";case "southwest":return"northeast";case "west":return"east";case "northwest":return"southeast";default:throw Error("ReverseDir error");}}function w(){for(var a=[],c=[],b=0;b<x.length;b++)a.push(x[b]);for(b=0;b<x.length;b++){var d=Math.round(Math.random()*(a.length-1));c.push(a[d]);d<a.length&&(a[d]=a[a.length-1]);a.pop()}return c}
function u(a,c){return{y:c.y+E(a),x:c.x+F(a)}}function G(a,c,b){for(var d=[],e=0;e<a.length;e++)d.push({});d[c.y][c.x]=0;for(var f=[{j:0,x:c.x,y:c.y}];0<f.length;){c=w();for(e=0;e<c.length;e++){var i=E(c[e]),g=F(c[e]),o={j:d[f[0].y][f[0].x]+1,x:f[0].x+g,y:f[0].y+i};0<=o.y&&(o.y<a.length&&0<=o.x&&o.x<a[o.y].length)&&(a[f[0].y+i][f[0].x+g].g&&"undefined"==typeof d[f[0].y+i][f[0].x+g])&&(d[o.y][o.x]=o.j,f.push(o))}f.shift();f.sort(D)}if("undefined"==typeof d[b.y][b.x])return t;a=b;for(b=[];0!=d[a.y][a.x];){c=
w();for(e=0;e<c.length;e++)if(f=u(c[e],a),i=d[f.y][f.x],"undefined"!=typeof i&&i<d[a.y][a.x]){b.push(N(c[e]));a=f;break}}return b=b.reverse()}function H(a,c,b){for(var d=0;d<b.length;d++){var e=G(a,c,b[d]);e?b[d].j=e.length:A(b[d],b)}b.sort(D);return b}function A(a,c){for(var b=0;b<c.length;b++)a===c[b]&&(b<c.length-1&&(c[b]=c[c.length-1]),c.pop())}function I(a,c,b){if(0==g[c][b].contents.length&&g[c][b].type!=a.type){var d=new l;d.d(c,b);d.i=0;d.h=a.h;d.l=a;d.m();g[c][b]=d}}function J(){for(var a=
0;a<r.length;a++)r[a].k();for(a=0;a<p.length;a++)p[a].k();for(a=0;a<K;a++)for(var c=0;c<L;c++){var b=M[a][c],d=g[a][c],e=$(b).attr("class").split(" "),f=["mapColumn"];f.push(d.b);d.f&&f.push(d.f);if(d.contents&&1<=d.contents.length){f.push(d.contents[0].b);for(var i=0;i<d.contents.length;i++)d.contents[i].selected&&f.push("mapSelected")}if(f.length!=e.length)$(b).removeClass(),$(b).addClass(f.join(" "));else for(i=0;i<f.length;i++)if(f[i]!=e[i]){$(b).removeClass();$(b).addClass(f.join(" "));break}}setTimeout(J,
100)}var p=[],r=[];n.prototype.d=function(a,c){this.a={y:a,x:c}};j.prototype=new n;j.prototype.b="empty";j.prototype.type=j;j.prototype.g=k;j.prototype.p=k;j.prototype.description="empty space";j.prototype.h=500;m.prototype=new n;m.prototype.b="wall";m.prototype.type=m;m.prototype.g=t;m.prototype.description="wall";m.prototype.h=500;h.prototype=new n;h.prototype.b="agent";h.prototype.type=h;h.prototype.selected=t;h.prototype.description="sandwich maker";h.prototype.c=q;h.prototype.e=function(){A(this,
p);this.c=q};h.prototype.n=function(){var a=G(g,this.a,this.moveTo);if(a){var c=g,b=this.a,a=u(a[0],b);c[a.y][a.x].contents.push(this);c[b.y][b.x].contents.pop();this.a=a}};h.prototype.q=function(){var a=g[this.a.y][this.a.x].contents;if(a&&1<a.length&&a[a.length-1]==this)for(var a=w(),c=0;c<a.length;c++){var b=u(a[c],this.a),d=g[b.y][b.x];if(d.g&&0==d.contents.length){this.moveTo=b;break}}};h.prototype.o=function(){for(var a=[],c=0;c<x.length;c++){var b=u(x[c],this.c.a);g[b.y][b.x].g&&a.push({y:b.y,
x:b.x})}1<a.length&&(a=H(g,this.a,a));if(0<a.length){for(c=0;c<a.length;c++){a:{b=a[c];b=g[b.y][b.x];if(0!=b.contents.length)for(var d=0;d<b.contents.length;d++)if(b.contents[d].type==this.type&&b.contents[d]!=this){b=t;break a}b=k}if(b){var e=a[c];break}}e||(e=a[0]);this.moveTo=e}else this.moveTo=this.c=q;e&&(e.y==this.a.y&&e.x==this.a.x)&&(this.c.i+=10)};h.prototype.r=function(){var a=Math.random();if(0.96<a&&0.999>a)for(var a=w(),c=0;c<a.length;c++)for(var b=w(),d=0;d<a.length;d++){var e=u(b[d],
u(a[c],this.a)),f;a:{try{if(0>e.y||e.y>g.length-1||0>e.x||e.x>g[e.y].length-1){f=t;break a}}catch(i){throw Error("Error in map bounds check");}f=k}if(f&&g[e.y][e.x].g){this.moveTo=e;break}if(this.moveTo)break}};h.prototype.k=function(){this.c&&this.o();if(this.moveTo&&(this.a.y!=this.moveTo.y||this.a.x!=this.moveTo.x))this.n();else if(!this.c&&0<r.length){for(var a=[],c=0;c<r.length;c++){for(var b=t,d=0;d<p.length;d++)if(p[d].c==r[c]){b=k;break}b||a.push(r[c].a)}0<a.length&&(1!=a.length&&H(g,this.a,
a),this.c=g[a[0].y][a[0].x])}else this.q();this.moveTo&&(this.a.y==this.moveTo.y&&this.a.x==this.moveTo.x)&&(this.moveTo=q);this.moveTo||this.r()};l.prototype=new n;l.prototype.g=t;l.prototype.type=l;l.prototype.description="something being built";l.prototype.i=q;l.prototype.h=q;l.prototype.l=q;l.prototype.m=function(){r.push(this)};l.prototype.e=function(){A(this,r);for(var a=0;a<p.length;a++)p[a].c==this&&(p[a].c=q)};l.prototype.k=function(){if(this.i>=this.h){var a=this.l,c=this.a.y,b=this.a.x;
a.d(c,b);a.contents=this.contents;this.e&&this.e();g[c][b]=a}else a=100*(this.i/this.h),0===a?this.f="markedForConstruction":25>=a?this.f="oneFourthConstructed":25<a&&50>=a?this.f="oneHalfConstructed":50<a&&75>=a?this.f="threeFourthsConstructed":75<a&&(this.f="almostConstructed")};var B=[{b:"agent",select:h},{b:"picker",select:0},{b:"inspector",select:2},{b:"delete",select:1},{b:"wall",select:m},{b:"emptySelector",select:j}],v=0;z=s=q;var x="north northeast east southeast south southwest west northwest".split(" "),
g=[],M=[],y=[],C=q,K=20,L=40;(function(){for(var a="#######################;# #     ######        #;# # ###      #    #   #;# # #   ######    #   #;# # #  ##         #   #;# # #  #          #   #;# # #  ############   #;# # #      #          #;#   ######   #        #;#######################".split(";"),c=[],b=0;b<a.length;b++){for(var d=[],e=0;e<a[b].length;e++){var f;switch(a[b][e]){case " ":f=new j;f.d(b,e);break;case "#":f=new m;f.d(b,e);break;case "@":f=new j;f.d(b,e);f.contents=new h;break;default:throw Error("AsciiArtToMap error");
}d.push(f)}c.push(d)}for(a=0;200>a;a++){b=[];for(d=0;200>d;d++)c[a]&&c[a][d]?b.push(c[a][d]):(e=new j,e.d(a,d),b.push(e));g.push(b)}})();(function(){for(var a=0;a<K;a++){var c=$('<div class="mapRow"></div>',b),b=$("#Map");c.appendTo(b);for(var d=[],e=0;e<L;e++){var f=$('<div class="mapColumn"</div>',c);(function(a,b){f.mousedown(function(){switch(B[v].select){case 0:1<=g[a][b].contents.length&&(s&&(z=s,z.selected=t),s=g[a][b].contents[g[a][b].contents.length-1],s.selected=k);0==g[a][b].contents.length&&
s&&(s.moveTo={y:a,x:b});break;case 1:if(0<g[a][b].contents.length){for(var c=0;c<g[a][b].contents.length;c++)g[a][b].contents[c].e&&g[a][b].contents[c].e();g[a][b].contents=[]}g[a][b].e&&g[a][b].e();c=new j;c.d(a,b);g[a][b]=c;break;case 2:if(0<g[a][b].contents.length){for(var c=["Here are: "+g[a][b].description],d=0;d<g[a][b].contents.length;d++)c.push(g[a][b].contents[d].description);c=c.join(", ")}else c="Here is: "+g[a][b].description;$(C).text(c);break;case h:c=new h;c.type&&c.type==h?g[a][b].p&&
0==g[a][b].contents.length&&(c.d(a,b),g[a][b].contents.push(c),p.push(c)):(c.d(a,b),g[a][b]=c);break;case m:I(new m,a,b);break;case j:I(new j,a,b);break;default:throw Error("Error in MapInteract");}})})(a,e);f.appendTo(c);d.push(f)}M.push(d)}})();(function(){for(var a=0;a<B.length;a++){var c=$('<div class="paletteRow"></div>'),b=$("#Palette");c.appendTo(b);(function(a){c.mousedown(function(){var b=v;v=a;$(y[v]).addClass("paletteSelected");$(y[b]).removeClass("paletteSelected")})})(a);$(c).addClass(B[a].b);
y.push(c)}v!=q&&$(y[v]).addClass("paletteSelected")})();(function(){C=$('<div class="textRow"></div>');var a=$("#TextBox");C.appendTo(a)})();J()})();
